export const adminModules = [
  { slug: "dashboard", label: "Dashboard", desc: "后台概览与快捷入口" },
  { slug: "project-management", label: "项目管理", desc: "查看项目并修改业务状态" },
  { slug: "cleanup", label: "数据清理与重分类", desc: "删除中国/无效项目，修复国家并重新分类" },
  { slug: "favorites", label: "收藏", desc: "查看收藏项目" },
  { slug: "key-projects", label: "重点项目", desc: "按评分筛选重点项目" },
  { slug: "contacted-owners", label: "已联系业主", desc: "查看已联系业主项目" },
  { slug: "purchased-docs", label: "已购买标书", desc: "查看标书购买状态" },
  { slug: "prequal-registered", label: "已报名资格预审", desc: "查看资格预审报名项目" },
  { slug: "submitted-bids", label: "已投标", desc: "查看已投标项目" },
  { slug: "abandoned", label: "已放弃", desc: "查看已放弃项目" },
  { slug: "awarded", label: "已授标", desc: "查看授标项目" },
  { slug: "completed", label: "项目完成", desc: "查看已完成项目" },
  { slug: "pending-verification", label: "待人工核实", desc: "查看待核实项目" },
  { slug: "data-sources", label: "数据源管理", desc: "查看官方数据源与运行状态" },
  { slug: "manual-review", label: "人工审核", desc: "审核项目进入正式库或驳回" },
  { slug: "recrawl", label: "重新抓取", desc: "调用 /api/cron/run 立即抓取" },
  { slug: "link-check", label: "链接检查", desc: "查看官方链接健康状态" },
  { slug: "run-logs", label: "运行日志", desc: "查看抓取运行记录" },
  { slug: "error-logs", label: "错误日志", desc: "查看抓取和系统错误" },
  { slug: "ai-logs", label: "AI日志", desc: "查看 AI 分析时间和置信度" },
  { slug: "push-logs", label: "推送日志", desc: "查看通知推送记录" },
  { slug: "system-settings", label: "系统设置", desc: "查看系统配置状态" },
  { slug: "admin-settings", label: "管理员设置", desc: "查看管理员安全配置" },
  { slug: "amount-thresholds", label: "金额门槛设置", desc: "查看金额门槛" },
  { slug: "countries", label: "国家管理", desc: "按国家查看项目" },
  { slug: "regions", label: "区域管理", desc: "按区域查看项目" },
  { slug: "industries", label: "行业管理", desc: "按行业查看项目" },
  { slug: "permissions", label: "用户权限", desc: "查看后台访问控制" }
] as const;
