import type { ProjectCandidate, SourceAdapter } from "./types";

async function fetchJson(url: string) {
  const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 20_000);
  try { const res = await fetch(url, { headers: { accept: "application/json,text/plain,*/*", "user-agent": "Brook-ZH tender monitor" }, signal: controller.signal, next: { revalidate: 0 } }); if (!res.ok) throw new Error(`${url} ${res.status}`); return res.json(); }
  finally { clearTimeout(timeout); }
}
function official(candidate: ProjectCandidate) { return candidate; }
function envKey(key: string, suffix: string) { return `SOURCE_${key.toUpperCase().replace(/-/g, "_")}_${suffix}`; }
function configurable(key: string, name: string, homepage: string): SourceAdapter { return { key, agencyName: name, homepage, crawlEntry: process.env[envKey(key, "URL")] || homepage, kind: "html", enabled: process.env[envKey(key, "ENABLED")] !== "false", async fetchCandidates() { const api = process.env[envKey(key, "JSON_URL")]; if (!api) throw new Error("未配置可自动抓取的 JSON/API 入口；请在后台或环境变量配置官方 API/RSS，不会伪造项目或成功状态"); const data = await fetchJson(api); const rows = Array.isArray(data) ? data : (data.items || data.results || data.data || []); return rows.map((r: any) => official({ sourceKey: key, section: /prequalification|pre-qualification|pq/i.test(`${r.stage || r.noticeType || r.procurement_method}`) ? "prequalification" : "tender", titleEn: r.title || r.titleEn || r.notice_title || "", country: r.country, owner: r.owner || r.borrower, financier: name, procurementNo: r.procurementNo || r.notice_number || r.id, packageNo: r.packageNo, amount: String(r.amount || ""), currency: r.currency || "USD", publishedAt: r.publishedAt || r.publication_date, deadlineAt: r.deadlineAt || r.deadline, procurementMethod: r.procurementMethod || r.procurement_method, stage: r.stage || r.noticeType, officialUrl: r.officialUrl || r.url || r.notice_url, documentUrl: r.documentUrl, noticeText: r.noticeText || r.description })).filter((r: ProjectCandidate) => r.titleEn && r.officialUrl); } }; }

export const officialSourceAdapters: SourceAdapter[] = [
  { key: "world-bank", agencyName: "World Bank Procurement", homepage: "https://projects.worldbank.org/en/projects-operations/procurement", crawlEntry: "https://search.worldbank.org/api/v2/procnotices", kind: "api", enabled: true, async fetchCandidates() { const data = await fetchJson("https://search.worldbank.org/api/v2/procnotices?format=json&rows=50&os=0"); const rows = Object.values(data?.procnotices ?? {}) as any[]; return rows.map((r) => official({ sourceKey: "world-bank", section: /prequalification|pre-qualification/i.test(r.procurement_method || r.notice_type || "") ? "prequalification" : "tender", titleEn: r.notice_title || r.project_name || "", country: r.country, owner: r.borrower_country, financier: "World Bank", procurementNo: r.notice_number, publishedAt: r.publication_date, deadlineAt: r.submission_deadline_date, procurementMethod: r.procurement_method, stage: r.notice_type, officialUrl: r.url || r.notice_url, noticeText: r.notice_text })).filter((r) => r.titleEn && r.officialUrl); } },
  configurable("adb", "Asian Development Bank Business Opportunities", "https://www.adb.org/projects/tenders"),
  configurable("afdb", "African Development Bank Procurement Notices", "https://www.afdb.org/en/projects-and-operations/procurement"),
  configurable("isdb", "Islamic Development Bank Procurement", "https://www.isdb.org/project-procurement"),
  configurable("ebrd", "European Bank for Reconstruction and Development Client e-Procurement", "https://ecepp.ebrd.com/"),
];
