import { scoreToStars } from "./rules";
import type { DashboardMetric, ProcurementSection, TenderProject } from "./types";

export const sectionLabels: Record<ProcurementSection, string> = {
  prequalification: "资格预审",
  tender: "正式招标",
  pipeline: "前瞻项目",
};

export const demoProjects: TenderProject[] = [
  {
    id: "pq-water-vn-001",
    section: "prequalification",
    titleZh: "越南中部供水管网扩建项目资格预审",
    titleEn: "Prequalification for Central Vietnam Water Network Expansion Project",
    country: "越南",
    region: "东南亚",
    industry: "供水",
    owner: "省级水务公司",
    financier: "亚洲开发银行",
    procurementNo: "ADB-VN-WTR-PQ-2026-01",
    contractNo: "CW-01",
    amountUsd: 68000000,
    amountSource: "官方金额",
    publishedAt: "2026-07-16",
    deadlineAt: "2026-08-28",
    procurementMethod: "International Competitive Bidding",
    stage: "资格预审",
    jointVentureRequirement: "允许联合体，需指定牵头方。",
    localRegistrationRequirement: "中标后需完成当地项目注册。",
    chinaParticipation: "可以参与",
    qualificationRequirementsZh: "近五年类似供水管网施工经验、满足财务能力和关键人员要求。",
    scopeZh: "建设输水管线、泵站、阀室、SCADA 接入及调试。",
    summaryZh: "项目为国际资格预审，外国承包商可参与，金额超过默认门槛。",
    riskTipsZh: ["当地注册风险", "汇率风险", "雨季施工风险"],
    score: 86,
    stars: scoreToStars(86),
    credibility: 92,
    aiUpdatedAt: "2026-07-17T00:00:00Z",
    status: "未截止",
    links: [
      { label: "资格预审公告", url: "https://example.org/official/pq-water-vn-001", type: "官方公告详情页", isOfficial: true, isValid: true },
      { label: "资格预审文件 PDF", url: "https://example.org/official/pq-water-vn-001.pdf", type: "官方资格预审文件", isOfficial: true, isValid: true, isPdf: true },
    ],
    addendaCount: 0,
    clarificationCount: 1,
  },
  {
    id: "tender-rail-kz-002",
    section: "tender",
    titleZh: "哈萨克斯坦铁路货运走廊土建工程正式招标",
    titleEn: "Invitation for Bids for Kazakhstan Rail Freight Corridor Civil Works",
    country: "哈萨克斯坦",
    region: "中亚",
    industry: "铁路",
    owner: "Kazakhstan Temir Zholy",
    financier: "欧洲复兴开发银行",
    procurementNo: "EBRD-KZ-RAIL-ICB-2026-02",
    packageNo: "LOT-2",
    amountUsd: 145000000,
    amountSource: "官方金额",
    bidSecurity: "投标价 2% 或等值保函",
    tenderFee: "500 USD",
    publishedAt: "2026-07-17",
    deadlineAt: "2026-09-10",
    openingAt: "2026-09-10T10:30:00+06:00",
    procurementMethod: "ICB / Open Tender",
    stage: "正式招标",
    jointVentureRequirement: "允许联合体，成员承担连带责任。",
    localRegistrationRequirement: "投标阶段不强制，中标后需税务登记。",
    chinaParticipation: "可以参与",
    qualificationRequirementsZh: "铁路土建、桥梁、轨道施工经验及年均营业额要求。",
    scopeZh: "路基、桥涵、轨道、站场及通信迁改配套工程。",
    summaryZh: "正式国际公开招标，工程范围明确，融资机构规则允许成员国企业参与。",
    riskTipsZh: ["付款币种风险", "冬季施工风险", "本地许可风险"],
    score: 91,
    stars: scoreToStars(91),
    credibility: 95,
    aiUpdatedAt: "2026-07-17T00:05:00Z",
    status: "补遗",
    links: [
      { label: "招标公告", url: "https://example.org/official/tender-rail-kz-002", type: "官方公告详情页", isOfficial: true, isValid: true },
      { label: "招标文件 PDF", url: "https://example.org/official/tender-rail-kz-002.pdf", type: "官方招标文件", isOfficial: true, isValid: true, isPdf: true },
      { label: "补遗 1", url: "https://example.org/official/tender-rail-kz-002-addendum-1.pdf", type: "官方补遗", isOfficial: true, isValid: true, isPdf: true },
    ],
    addendaCount: 1,
    clarificationCount: 0,
  },
  {
    id: "pipe-ppp-br-003",
    section: "pipeline",
    titleZh: "巴西港口物流园 PPP 前瞻项目",
    titleEn: "Brazil Port Logistics Park PPP Pipeline Project",
    country: "巴西",
    region: "拉丁美洲",
    industry: "港口 / 物流园",
    owner: "州投资伙伴计划办公室",
    financier: "CAF",
    totalInvestmentUsd: 220000000,
    amountUsd: 120000000,
    amountSource: "AI估算",
    procurementMethod: "PPP Pipeline",
    stage: "前瞻项目",
    expectedTenderTime: "2026 Q4",
    jointVentureRequirement: "预计允许联合体，需等待正式文件确认。",
    localRegistrationRequirement: "预计需设立项目公司。",
    chinaParticipation: "待人工核实",
    qualificationRequirementsZh: "正式资格条件尚未发布。",
    scopeZh: "港口后方物流园、道路连接线、仓储设施和公用工程。",
    summaryZh: "融资和可研信息已出现，但中国企业参与资格需等待正式采购文件确认。",
    riskTipsZh: ["PPP融资风险", "税务风险", "政治审批风险"],
    score: 74,
    stars: scoreToStars(74),
    credibility: 78,
    aiUpdatedAt: "2026-07-17T00:10:00Z",
    status: "待人工核实",
    links: [
      { label: "PPP 管线公告", url: "https://example.org/official/pipe-ppp-br-003", type: "官方采购计划", isOfficial: true, isValid: true },
      { label: "GPN", url: "https://example.org/official/pipe-ppp-br-003-gpn.pdf", type: "官方GPN", isOfficial: true, isValid: true, isPdf: true },
    ],
    addendaCount: 0,
    clarificationCount: 0,
    knownConsultant: "待人工核实",
    knownDesigner: "待人工核实",
    knownContractor: "无公开信息",
  },
];

export function getProjectsBySection(section: ProcurementSection) {
  return demoProjects.filter((project) => project.section === section).sort((a, b) => b.score - a.score);
}

export function getProjectById(id: string) {
  return demoProjects.find((project) => project.id === id);
}

export function dashboardMetrics(projects = demoProjects): DashboardMetric[] {
  const today = "2026-07-17";
  const todayProjects = projects.filter((project) => project.publishedAt === today);
  return [
    { label: "今日新增项目数量", value: todayProjects.length },
    { label: "今日符合条件项目数量", value: projects.filter((project) => project.chinaParticipation === "可以参与" && project.status !== "已取消" && project.status !== "已授标").length, tone: "success" },
    { label: "今日新增资格预审数量", value: todayProjects.filter((project) => project.section === "prequalification").length },
    { label: "今日新增正式招标数量", value: todayProjects.filter((project) => project.section === "tender").length },
    { label: "今日新增前瞻项目数量", value: todayProjects.filter((project) => project.section === "pipeline").length },
    { label: "即将截止项目数量", value: projects.filter((project) => project.deadlineAt).length, tone: "warning" },
    { label: "今日延期项目数量", value: projects.filter((project) => project.status === "延期").length },
    { label: "今日补遗项目数量", value: projects.filter((project) => project.addendaCount > 0).length, tone: "warning" },
    { label: "今日澄清项目数量", value: projects.filter((project) => project.clarificationCount > 0).length },
    { label: "今日授标项目数量", value: projects.filter((project) => project.status === "已授标").length },
    { label: "今日取消项目数量", value: projects.filter((project) => project.status === "已取消").length },
    { label: "数据源运行状态", value: "正常" },
    { label: "AI运行状态", value: "正常" },
    { label: "最近一次抓取时间", value: "2026-07-17 00:00 UTC" },
    { label: "最近一次推送时间", value: "2026-07-17 00:06 UTC" },
    { label: "今日抓取成功率", value: "100%", tone: "success" },
    { label: "当前监控国家数量", value: 56 },
    { label: "当前监控机构数量", value: 18 },
  ];
}
