import { unstable_noStore as noStore } from "next/cache";
import { FORBIDDEN_PROCUREMENT, isEngineeringProcurement, scoreToStars } from "./rules";
import { getServiceSupabase } from "./supabase";
import type { DashboardMetric, ProcurementSection, TenderProject } from "./types";
export const sectionLabels: Record<ProcurementSection, string> = { prequalification: "资格预审", tender: "正式招标", pipeline: "前瞻项目" };
export const demoProjects: TenderProject[] = [];
export type ProjectFilters = { q?: string; country?: string; region?: string; industry?: string; stage?: string; amountMin?: number; publishedFrom?: string; publishedTo?: string; deadlineFrom?: string; deadlineTo?: string; financier?: string; chinaParticipation?: string; status?: string; sort?: string; page?: number; pageSize?: number; today?: boolean; upcoming?: boolean; pending?: boolean };
export function londonDate(date = new Date()) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/London", year:"numeric", month:"2-digit", day:"2-digit" }).format(date); }
export function isActiveProcurement(p: TenderProject) {
  const text = `${p.titleEn} ${p.titleZh} ${p.procurementMethod} ${p.stage}`;
  return !FORBIDDEN_PROCUREMENT.test(text) && !["已授标","已取消","已完成"].includes(p.status) && (!p.deadlineAt || new Date(p.deadlineAt).getTime() > Date.now()) && p.chinaParticipation !== "不可参与";
}
export function isEligibleTender(p: TenderProject) { return p.section === "tender" && Boolean(p.deadlineAt) && isActiveProcurement(p) && isEngineeringProcurement({ title:p.titleEn, procurementType:p.procurementMethod, stage:p.stage }); }
export async function getProjectsBySection(section: ProcurementSection, filters: ProjectFilters = {}) { const source=(await loadProjects()).filter(p=>p.section===section).filter(p=>section!=="tender"||isEligibleTender(p)); return filterAndSortProjects(source,filters); }
export function filterAndSortProjects(projects: TenderProject[], filters: ProjectFilters) {
 let rows=projects.filter(p=>{ const q=filters.q?.toLowerCase().trim(); if(q&&!`${p.titleZh} ${p.titleEn} ${p.country} ${p.owner} ${p.financier} ${p.procurementNo??""}`.toLowerCase().includes(q))return false; if(filters.country&&p.country!==filters.country)return false; if(filters.region&&p.region!==filters.region)return false; if(filters.industry&&p.industry!==filters.industry)return false; if(filters.stage&&p.stage!==filters.stage)return false; if(filters.financier&&p.financier!==filters.financier)return false; if(filters.chinaParticipation&&p.chinaParticipation!==filters.chinaParticipation)return false; if(filters.status&&displayStatus(p)!==filters.status)return false; if(filters.pending&&!(p.reviewStatus==="pending"||p.status==="待人工核实"))return false; if(filters.today&&londonDate(new Date(p.createdAt??0))!==londonDate())return false; if(filters.upcoming&&(!p.deadlineAt||new Date(p.deadlineAt).getTime()<=Date.now()||new Date(p.deadlineAt).getTime()>Date.now()+7*864e5))return false; if(filters.amountMin&&(!p.amountUsd||p.amountUsd<filters.amountMin))return false; if(filters.publishedFrom&&(!p.publishedAt||p.publishedAt<filters.publishedFrom))return false; if(filters.publishedTo&&(!p.publishedAt||p.publishedAt>filters.publishedTo))return false; if(filters.deadlineFrom&&(!p.deadlineAt||p.deadlineAt<filters.deadlineFrom))return false; if(filters.deadlineTo&&(!p.deadlineAt||p.deadlineAt>filters.deadlineTo))return false; return true; });
 rows=rows.sort((a,b)=>filters.sort==="deadline"?String(a.deadlineAt??"9999").localeCompare(String(b.deadlineAt??"9999")):filters.sort==="published"?String(b.publishedAt??"").localeCompare(String(a.publishedAt??"")):filters.sort==="amount"?(b.amountUsd??0)-(a.amountUsd??0):b.score-a.score); const page=Math.max(1,filters.page??1),size=Math.min(100,Math.max(1,filters.pageSize??20)); return {rows:rows.slice((page-1)*size,page*size),total:rows.length,page,pageSize:size};
}
export function displayStatus(p:TenderProject){if(p.reviewStatus==="pending"||p.status==="待人工核实")return "待人工核实";if(p.deadlineAt&&new Date(p.deadlineAt).getTime()-Date.now()<=7*864e5)return "即将截止";return "正在招标";}
export async function getProjectById(id:string){return(await loadProjects()).find(p=>p.id===id);}
export async function loadProjects():Promise<TenderProject[]>{noStore();try{const supabase=getServiceSupabase();const{data,error}=await supabase.from("projects").select("*, project_links(*)").neq("gate","blocked").order("created_at",{ascending:false}).limit(1000);if(error)throw error;return(data??[]).map(mapProject).filter(p=>p.links.some(l=>l.isOfficial&&l.isValid)&&p.status!=="已完成");}catch{return[];}}
export function dashboardMetrics(projects:TenderProject[]):DashboardMetric[]{const today=londonDate();const added=(p:TenderProject)=>londonDate(new Date(p.createdAt??0))===today;const active=projects.filter(isActiveProcurement);return[{label:"今日新增项目数量",value:projects.filter(added).length},{label:"今日符合条件项目数量",value:active.filter(added).length,tone:"success"},{label:"今日新增资格预审数量",value:active.filter(p=>p.section==="prequalification"&&added(p)).length},{label:"今日新增正式招标数量",value:active.filter(p=>isEligibleTender(p)&&added(p)).length},{label:"今日新增前瞻项目数量",value:projects.filter(p=>p.section==="pipeline"&&added(p)).length},{label:"即将截止项目数量",value:active.filter(p=>p.deadlineAt&&new Date(p.deadlineAt).getTime()<=Date.now()+7*864e5).length,tone:"warning"},{label:"待人工核实",value:projects.filter(p=>p.reviewStatus==="pending"||p.status==="待人工核实").length,tone:"warning"}];}
function mapProject(row:any):TenderProject{const score=Number(row.ai_score??0);return{id:row.id,section:row.section,titleZh:chineseTitle(row.title_zh,row.title_en,row.country),titleEn:row.title_en,country:row.country??"官方未公布",region:row.region??"官方未公布",industry:row.industry??"官方未公布",owner:row.owner??"官方未公布",financier:row.financier??"官方未公布",procurementNo:row.procurement_no,contractNo:row.contract_no,packageNo:row.package_no,amountUsd:row.amount_usd?Number(row.amount_usd):undefined,amountCurrency:row.amount_currency??"USD",amountSource:row.amount_is_official?"官方金额":row.amount_is_ai_estimate?"AI估算":"待人工核实",publishedAt:row.published_at,deadlineAt:row.deadline_at,procurementMethod:row.procurement_method??"官方未公布",stage:row.stage??"官方未公布",jointVentureRequirement:row.joint_venture_requirements??"官方未公布",localRegistrationRequirement:row.local_registration_requirements??"官方未公布",chinaParticipation:row.china_eligible===true?"可以参与":row.china_eligible===false?"不可参与":"待人工核实",qualificationRequirementsZh:row.qualification_requirements_zh??"官方未公布",scopeZh:row.scope_zh??"官方未公布",summaryZh:row.summary_zh??"官方未公布",riskTipsZh:row.risks_zh??[],score,stars:scoreToStars(score),credibility:row.credibility??0,aiUpdatedAt:row.ai_analyzed_at??"",status:row.status,links:(row.project_links??[]).map((l:any)=>({label:l.link_type,type:l.link_type,url:l.url,isOfficial:l.is_official,isValid:(l.http_status??200)<400,isPdf:l.is_pdf,httpStatus:l.http_status})),addendaCount:0,clarificationCount:0,isFavorite:row.is_favorite,participatedCompanyName:row.participated_company_name,completedAt:row.completed_at,reviewStatus:row.review_status,createdAt:row.created_at};}

function chineseTitle(zh:unknown,en:unknown,country:unknown){const z=String(zh??"").trim();if(/[\u3400-\u9fff]/.test(z))return z;const text=String(en??"").toLowerCase();const kind=/bridge/.test(text)?"桥梁":/road|highway/.test(text)?"道路":/rail/.test(text)?"铁路":/water|wastewater/.test(text)?"供排水":/power|transmission/.test(text)?"电力":/port/.test(text)?"港口":/airport/.test(text)?"机场":"工程建设";return `${String(country??"海外")}${kind}招标项目（中文待校核）`;}
