import Link from "next/link";
import { notFound } from "next/navigation";
import { isAdminSession } from "@/lib/admin-auth";
import { displayStatus, getProjectsBySection, sectionLabels } from "@/lib/projects";
import { toggleFavorite } from "@/app/admin/admin-actions";
import type { ProcurementSection, TenderProject } from "@/lib/types";
export default async function SectionPage({params,searchParams}:{params:Promise<{section:ProcurementSection}>,searchParams:Promise<Record<string,string|undefined>>}){const{section}=await params;const sp=await searchParams;if(!sectionLabels[section])notFound();const result=await getProjectsBySection(section,{q:sp.q,country:sp.country,status:sp.status,sort:sp.sort,page:sp.page?Number(sp.page):1,today:sp.today==="1",upcoming:sp.upcoming==="1",pending:sp.pending==="1"});const admin=await isAdminSession();return <main className="shell"><Link href="/">← 返回仪表盘</Link><div className="list-heading"><div><p className="eyebrow">实时读取 Supabase</p><h1>{sectionLabels[section]}</h1><p>{section==="tender"?"仅展示尚可投标、截止日期有效的工程建设类项目；咨询服务及已授标、签约、成交、关闭、取消、过期项目均已排除。":"仅展示真实官方数据，不使用演示项目。"}</p></div><strong className="count">{result.total} 个项目</strong></div><form className="filters"><input name="q" placeholder="搜索项目/编号/业主" defaultValue={sp.q}/><input name="country" placeholder="国家" defaultValue={sp.country}/><select name="status" defaultValue={sp.status??""}><option value="">全部有效状态</option><option>正在招标</option><option>即将截止</option><option>待人工核实</option></select><select name="sort" defaultValue={sp.sort??"score"}><option value="score">推荐排序</option><option value="deadline">截止日期</option><option value="published">发布日期</option><option value="amount">金额</option></select><button className="button">筛选</button></form><div className="project-list">{result.rows.length===0?<div className="card empty">暂无符合当前条件的真实项目</div>:result.rows.map(p=><ProjectCard key={p.id} p={p} admin={admin}/>)}</div><nav className="pager">{result.page>1&&<Link href={pageUrl(sp,result.page-1)}>上一页</Link>}<span>第 {result.page} 页</span>{result.total>result.page*result.pageSize&&<Link href={pageUrl(sp,result.page+1)}>下一页</Link>}</nav></main>}
function ProjectCard({p,admin}:{p:TenderProject;admin:boolean}){return <article className="card project-card"><div className="project-title"><div><h2><Link href={`/projects/${p.section}/${p.id}`}>{p.titleZh}</Link></h2><p>{p.titleEn}</p><span className={`status ${displayStatus(p)==="即将截止"?"urgent":""}`}>{displayStatus(p)}</span></div></div><dl className="project-facts"><Fact label="国家" value={p.country}/><Fact label="项目编号" value={p.procurementNo??"官方未公布"}/><Fact label="采购类型" value={p.procurementMethod}/><Fact label="发布日期" value={dateTime(p.publishedAt)}/><Fact label="截止日期" value={dateTime(p.deadlineAt)}/><Fact label="融资机构" value={p.financier}/><Fact label="工程体量/项目金额" value={money(p)}/></dl><div className="card-actions">{admin?<form action={toggleFavorite}><input type="hidden" name="id" value={p.id}/><input type="hidden" name="favorite" value={String(Boolean(p.isFavorite))}/><button className="favorite">{p.isFavorite?"★ 取消收藏":"☆ 收藏"}</button></form>:<Link className="favorite" href="/admin/login">☆ 登录后收藏</Link>}{p.links.find(l=>l.isOfficial&&l.isValid)?<a className="button small" href={p.links.find(l=>l.isOfficial&&l.isValid)!.url} target="_blank" rel="noreferrer">官方详情 ↗</a>:null}</div></article>}
function Fact({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function money(p:TenderProject){return p.amountUsd&&p.amountSource==="官方金额"?`${p.amountCurrency??"USD"} ${p.amountUsd.toLocaleString("zh-CN")}`:"官方未公布"}
function dateTime(v?:string){return v?new Intl.DateTimeFormat("zh-CN",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(v)).replaceAll("/","-"):"官方未公布"}
function pageUrl(sp:Record<string,string|undefined>,page:number){const q=new URLSearchParams();Object.entries(sp).forEach(([k,v])=>{if(v&&k!=="page")q.set(k,v)});q.set("page",String(page));return`?${q}`}
